use the wthread struct to convey the gnuplot command line choice from main() to doProfile() and thus provide / restore the logical basis that the gnuplot feature can be anabled via the command line switch at all.
Note: I did not test the gnuplot feature itself.

I merely fixed the compilation with icc.

Thanks go to icc for reporting
"
clients/src/mapiclient/stethoscope.c(429): error #593: variable "gnuplot" was set but never used
  int gnuplot = 0;
      ^
"