tried to solve
========
icc -no-gcc -DHAVE_CONFIG_H -I. -I/ufs/manegold/_/scratch0/Monet/Testing/Current/pathfinder/compiler/algebra -I../.. -I/ufs/manegold/_/scratch0/Monet/Testing/Current/pathfinder/compiler/algebra -I../include -I/ufs/manegold/_/scratch0/Monet/Testing/Current/pathfinder/compiler/algebra/../include -I/ufs/manegold/_/scratch0/Monet/Testing/Current/.ntv.64.64.d..PREFIX./MONETDB/include/MonetDB -I/ufs/manegold/_/scratch0/Monet/Testing/Current/.ntv.64.64.d..PREFIX./MONETDB/include/MonetDB/common -I/ufs/manegold/_/scratch0/Monet/Testing/Current/.ntv.64.64.d..PREFIX./MONETDB/include/MonetDB/gdk -I/ufs/manegold/_/scratch0/Monet/Testing/Current/.ntv.64.64.d..PREFIX./MONETDB/include/MonetDB/monet -I/ufs/manegold/_/scratch0/Monet/Testing/Current/.ntv.64.64.d..PREFIX./MONETDB/include/MonetDB/plain -I/ufs/manegold/_/scratch0/Monet/Testing/Current/.ntv.64.64.d..PREFIX./MONETDB/include/MonetDB/contrib -I/ufs/manegold/_/scratch0/Monet/Testing/Current/.ntv.64.64.d..PREFIX./MONETDB/include/MonetDB/mapi -I/ufs/manegold/_/scratch0/Monet/Testing/Current/.ntv.64.64.d..PREFIX./MONETDB/include/MonetDB/C -DLIBALGEBRA -g -we140 -wd1418 -c99 -Wall -w2 -we266 -Werror -wd1418,1419,279,310,981,810,444,193,111,177,171,181,764,269,108,188,1357,102,70,1572 -c /ufs/manegold/_/scratch0/Monet/Testing/Current/pathfinder/compiler/algebra/builtins.c  -KPIC -DPIC -o .libs/libalgebra_la-builtins.o
/ufs/manegold/_/scratch0/Monet/Testing/Current/pathfinder/compiler/algebra/builtins.c(1284): error #869: parameter "loop" was never referenced
  PFbui_fn_zero_or_one (const PFla_op_t *loop __attribute__((unused)),
                                         ^
compilation aborted for /ufs/manegold/_/scratch0/Monet/Testing/Current/pathfinder/compiler/algebra/builtins.c (code 2)
make[5]: *** [libalgebra_la-builtins.lo] Error 1
========

by adding

========
    (void) loop; /* pacify picky compilers that do not understand
                    "__attribute__((unused))" */
========

but got

========
icc -no-gcc -DHAVE_CONFIG_H -I. -I/ufs/manegold/_/scratch0/Monet/Testing/Current/pathfinder/compiler/algebra -I../.. -I/ufs/manegold/_/scratch0/Monet/Testing/Current/pathfinder/compiler/algebra -I../include -I/ufs/manegold/_/scratch0/Monet/Testing/Current/pathfinder/compiler/algebra/../include -I/ufs/manegold/_/scratch0/Monet/Testing/Current/.ntv.64.64.d..PREFIX./MONETDB/include/MonetDB -I/ufs/manegold/_/scratch0/Monet/Testing/Current/.ntv.64.64.d..PREFIX./MONETDB/include/MonetDB/common -I/ufs/manegold/_/scratch0/Monet/Testing/Current/.ntv.64.64.d..PREFIX./MONETDB/include/MonetDB/gdk -I/ufs/manegold/_/scratch0/Monet/Testing/Current/.ntv.64.64.d..PREFIX./MONETDB/include/MonetDB/monet -I/ufs/manegold/_/scratch0/Monet/Testing/Current/.ntv.64.64.d..PREFIX./MONETDB/include/MonetDB/plain -I/ufs/manegold/_/scratch0/Monet/Testing/Current/.ntv.64.64.d..PREFIX./MONETDB/include/MonetDB/contrib -I/ufs/manegold/_/scratch0/Monet/Testing/Current/.ntv.64.64.d..PREFIX./MONETDB/include/MonetDB/mapi -I/ufs/manegold/_/scratch0/Monet/Testing/Current/.ntv.64.64.d..PREFIX./MONETDB/include/MonetDB/C -DLIBALGEBRA -g -we140 -wd1418 -c99 -Wall -w2 -we266 -Werror -wd1418,1419,279,310,981,810,444,193,111,177,171,181,764,269,108,188,1357,102,70,1572 -c /ufs/manegold/_/scratch0/Monet/Testing/Current/pathfinder/compiler/algebra/builtins.c  -KPIC -DPIC -o .libs/libalgebra_la-builtins.o
/ufs/manegold/_/scratch0/Monet/Testing/Current/pathfinder/compiler/algebra/builtins.c(1317):  (col. 5)internal error: 0_0

compilation aborted for /ufs/manegold/_/scratch0/Monet/Testing/Current/pathfinder/compiler/algebra/builtins.c (code 4)
make[5]: *** [libalgebra_la-builtins.lo] Error 1
========

sorry, giving up ... (for now?)