propagated fix from monet:
When using alloca(3) in a shared library, Intel's "C++ Compiler for
32-bit applications, Version 5.0.1 Beta Build 010528D0" seems to require
another reference to alloca(3) in the file that contains the main(),
otherwise it complains about an "undefined reference to `_alloca\_probe'"
when linking the shared library to the executable.