temporary HACK: skip q03.xq on SunOS
XMark q03.xq current causes `pf -A` to segfault (on all platforms), and then
(only on SunOS), Mtest.py stops with

[...]
05:49:20> compiler/pf-A_XMark  (<=180,180,180) ...1154058860.a: removed
   5.388s
pf-A_XMark.stable.out.FILTERED and pf-A_XMark.test.out.FILTERED are equal.
pf-A_XMark.stable.err.FILTERED and pf-A_XMark.test.err.FILTERED differ SIGNIFICANTLY!
Traceback (most recent call last):
  File "/export/scratch1/monet/monet.GNU.32.32.d.10572/MonetDB/.GNU.32.32.d-SunOS5.10/bin/Mtest.py", line 3315, in ?
    main(sys.argv)
  File "/export/scratch1/monet/monet.GNU.32.32.d.10572/MonetDB/.GNU.32.32.d-SunOS5.10/bin/Mtest.py", line 3152, in main
    t, elem = PerformDir(env, d, [], BusyPorts)
  File "/export/scratch1/monet/monet.GNU.32.32.d.10572/MonetDB/.GNU.32.32.d-SunOS5.10/bin/Mtest.py", line 964, in PerformDir
    os.makedirs(TSTTRGDIR)
  File "/opt/csw/lib/python2.3/os.py", line 153, in makedirs
    makedirs(head, mode)
  File "/opt/csw/lib/python2.3/os.py", line 154, in makedirs
    mkdir(name, mode)
OSError: [Errno 20] Not a directory: '/export/scratch1/monet/monet.GNU.32.32.d.10572/pathfinder/SunOS5.10/mTests/compiler/core/tests'

*possibly* due to the segfault? --- we shall see tomorrow...